# R CMD check --as-cran forestChange_0.1.tar.gz
# R CMD check --as-cran forestChange_0.2.tar.gz
# R CMD check --as-cran forestChange_0.3.tar.gz
# R CMD check --as-cran forestChange_0.4.tar.gz
# R CMD check --as-cran forestChange_0.5.tar.gz
# R CMD check --as-cran forestChange_0.6.tar.gz
# R CMD check --as-cran forestChange_0.7.tar.gz
# R CMD check --as-cran forestChange_0.8.tar.gz
# R CMD check --as-cran forestChange_1.0.tar.gz
# R CMD check --as-cran ecoChange_1.0.tar.gz
# R CMD check --as-cran forestChange_1.1.tar.gz
# R CMD check --as-cran forestChange_1.2.tar.gz
# R CMD check --as-cran ecochange_1.0.tar.gz
# R CMD check --as-cran ecochange_1.1.tar.gz
# R CMD check --as-cran ecochange_1.2.tar.gz
# R CMD check --as-cran ecochange_1.3.tar.gz
# R CMD check --as-cran ecochange_1.4.tar.gz
# R CMD check --as-cran ecochange_1.5.tar.gz
# R CMD check --as-cran ecochange_1.6.tar.gz
# R CMD check --as-cran ecochange_1.7.tar.gz
# R CMD check --as-cran ecochange_1.8.tar.gz
# R CMD check --as-cran ecochange_1.9.tar.gz
# R CMD check --as-cran ecochange_2.0.tar.gz
# R CMD check --as-cran ecochange_2.1.tar.gz
# R CMD check --as-cran ecochange_2.2.tar.gz
# R CMD check --as-cran ecochange_2.3.tar.gz
# R CMD check --as-cran ecochange_2.4.tar.gz
# R CMD check --as-cran ecochange_2.5.tar.gz
# R CMD check --as-cran ecochange_2.6.tar.gz
# R CMD check --as-cran ecochange_2.7.tar.gz
# R CMD check --as-cran ecochange_2.8.tar.gz
# R CMD check --as-cran ecochange_2.9.tar.gz
R CMD check --as-cran ecochange_2.9.1.tar.gz
